###############################################################################
# WF_OP
###############################################################################

text_sensor:

  - platform: template
    id: output_priority
    name: "Output Priority"
    lambda: |-
      switch ((uint16_t)id(output_priority_raw).state) {
        case 0: return {"GPB"};
        case 1: return {"PGB"};
        case 2: return {"PBG"};
        case 3: return {"MKS"};
        default: return {"Unknown"};
      }

  - platform: template
    id: operating_mode
    name: "Operating Mode"
    lambda: |-
      switch ((uint16_t)id(operating_mode_raw).state) {
        case 0: return {"APP"};
        case 1: return {"UPS"};
        case 2: return {"GEN"};
        default: return {"Unknown"};
      }

sensor:

###############################################################################
# RAW
###############################################################################

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: output_priority_raw
    internal: true
    address: 0x0210
    register_type: holding
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: operating_mode_raw
    internal: true
    address: 0x0211
    register_type: holding
    value_type: U_WORD

###############################################################################
# Phase A
###############################################################################

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_output_voltage
    name: "Phase A Output Voltage"
    address: 0x0218
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    filters: [{multiply: 0.1}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_output_frequency
    name: "Phase A Output Frequency"
    address: 0x0219
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "Hz"
    device_class: frequency
    state_class: measurement
    accuracy_decimals: 2
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_output_current
    name: "Phase A Output Current"
    address: 0x021A
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "A"
    device_class: current
    state_class: measurement
    accuracy_decimals: 2
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_small_output_current
    name: "Phase A Small Output Current"
    address: 0x021B
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "A"
    entity_category: diagnostic
    accuracy_decimals: 2
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_output_active_power
    name: "Phase A Output Active Power"
    address: 0x021C
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_output_apparent_power
    name: "Phase A Output Apparent Power"
    address: 0x021D
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "VA"
    device_class: apparent_power
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_load_percentage
    name: "Phase A Load Percentage"
    address: 0x0220
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "%"
    state_class: measurement
    accuracy_decimals: 1
    filters: [{multiply: 0.1}]

###############################################################################
# Phase B
###############################################################################

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_b_output_voltage
    name: "Phase B Output Voltage"
    address: 0x0230
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    filters: [{multiply: 0.1}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_b_output_frequency
    name: "Phase B Output Frequency"
    address: 0x0231
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "Hz"
    device_class: frequency
    state_class: measurement
    accuracy_decimals: 2
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_b_output_current
    name: "Phase B Output Current"
    address: 0x0232
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "A"
    device_class: current
    state_class: measurement
    accuracy_decimals: 2
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_b_small_output_current
    name: "Phase B Small Output Current"
    address: 0x0233
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "A"
    entity_category: diagnostic
    accuracy_decimals: 2
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_b_output_active_power
    name: "Phase B Output Active Power"
    address: 0x0234
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_b_output_apparent_power
    name: "Phase B Output Apparent Power"
    address: 0x0235
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "VA"
    device_class: apparent_power
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_b_load_percentage
    name: "Phase B Load Percentage"
    address: 0x0238
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "%"
    state_class: measurement
    accuracy_decimals: 1
    filters: [{multiply: 0.1}]

###############################################################################
# Phase C
###############################################################################

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_c_output_voltage
    name: "Phase C Output Voltage"
    address: 0x0248
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    filters: [{multiply: 0.1}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_c_output_frequency
    name: "Phase C Output Frequency"
    address: 0x0249
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "Hz"
    device_class: frequency
    state_class: measurement
    accuracy_decimals: 2
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_c_output_current
    name: "Phase C Output Current"
    address: 0x024A
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "A"
    device_class: current
    state_class: measurement
    accuracy_decimals: 2
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_c_small_output_current
    name: "Phase C Small Output Current"
    address: 0x024B
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "A"
    entity_category: diagnostic
    accuracy_decimals: 2
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_c_output_active_power
    name: "Phase C Output Active Power"
    address: 0x024C
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_c_output_apparent_power
    name: "Phase C Output Apparent Power"
    address: 0x024D
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "VA"
    device_class: apparent_power
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_c_load_percentage
    name: "Phase C Load Percentage"
    address: 0x0250
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "%"
    state_class: measurement
    accuracy_decimals: 1
    filters: [{multiply: 0.1}]

###############################################################################
# Phase A Energy Counters
###############################################################################

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_daily_energy
    name: "Phase A Daily Energy"
    address: 0x0221
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_monthly_energy
    name: "Phase A Monthly Energy"
    address: 0x0223
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_yearly_energy
    name: "Phase A Yearly Energy"
    address: 0x0225
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_total_energy
    name: "Phase A Total Energy"
    address: 0x0227
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

###############################################################################
# Phase B Energy Counters
###############################################################################

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_b_daily_energy
    name: "Phase B Daily Energy"
    address: 0x0239
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_b_monthly_energy
    name: "Phase B Monthly Energy"
    address: 0x023B
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_b_yearly_energy
    name: "Phase B Yearly Energy"
    address: 0x023D
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_b_total_energy
    name: "Phase B Total Energy"
    address: 0x023F
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

###############################################################################
# Phase C Energy Counters
###############################################################################

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_c_daily_energy
    name: "Phase C Daily Energy"
    address: 0x0251
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_c_monthly_energy
    name: "Phase C Monthly Energy"
    address: 0x0253
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_c_yearly_energy
    name: "Phase C Yearly Energy"
    address: 0x0255
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_c_total_energy
    name: "Phase C Total Energy"
    address: 0x0257
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    filters:
      - multiply: 0.01