###############################################################################
# WF_BAT
###############################################################################

text_sensor:

  - platform: template
    id: battery_type
    name: "Battery Type"
    lambda: |-
      switch ((uint16_t)id(battery_type_raw).state) {
        case 0: return {"Lead Acid"};
        case 1: return {"Flooded"};
        case 2: return {"Ternary Lithium"};
        case 3: return {"LiFePO4"};
        case 4: return {"Custom"};
        default: return {"Unknown"};
      }

  - platform: template
    id: charging_status
    name: "Charging Status"
    lambda: |-
      switch ((uint16_t)id(charging_status_raw).state) {
        case 0: return {"Not Charging"};
        case 1: return {"CC/CV"};
        case 2: return {"Float"};
        case 3: return {"Equalization"};
        default: return {"Unknown"};
      }

sensor:

#
# RAW
#

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: battery_type_raw
    internal: true
    address: 0x0150
    register_type: holding
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: charging_status_raw
    internal: true
    address: 0x0176
    register_type: holding
    value_type: U_WORD

#
# Battery
#

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: battery_percentage
    name: "Battery Percentage"
    address: 0x0152
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "%"
    device_class: battery
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: positive_bus_voltage
    name: "Positive Bus Voltage"
    address: 0x0154
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: positive_battery_voltage
    name: "Positive Battery Voltage"
    address: 0x0155
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: positive_battery_discharge_current
    name: "Positive Battery Discharge Current"
    address: 0x0156
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: positive_battery_charge_current
    name: "Positive Battery Charge Current"
    address: 0x0157
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: positive_overvoltage_alarm
    name: "Positive Overvoltage Alarm Voltage"
    address: 0x0158
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: positive_low_voltage_alarm
    name: "Positive Low Voltage Alarm Voltage"
    address: 0x0159
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: positive_output_cutoff_voltage
    name: "Positive Output Cutoff Voltage"
    address: 0x015C
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: positive_output_cutoff_time
    name: "Positive Output Cutoff Time"
    address: 0x015D
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: h

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: positive_battery_power
    name: "Positive Battery Power"
    address: 0x015E
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: W
    device_class: power
    state_class: measurement
    filters:
      - multiply: 10

#
# Negative Battery
#

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: negative_bus_voltage
    name: "Negative Bus Voltage"
    address: 0x0164
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: negative_battery_voltage
    name: "Negative Battery Voltage"
    address: 0x0165
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: negative_battery_discharge_current
    name: "Negative Battery Discharge Current"
    address: 0x0166
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: negative_battery_charge_current
    name: "Negative Battery Charge Current"
    address: 0x0167
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: negative_overvoltage_alarm
    name: "Negative Overvoltage Alarm Voltage"
    address: 0x0168
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: negative_low_voltage_alarm
    name: "Negative Low Voltage Alarm Voltage"
    address: 0x0169
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: negative_output_cutoff_voltage
    name: "Negative Output Cutoff Voltage"
    address: 0x016C
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: negative_output_cutoff_time
    name: "Negative Output Cutoff Time"
    address: 0x016D
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: h

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: negative_battery_power
    name: "Negative Battery Power"
    address: 0x016E
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: W
    device_class: power
    state_class: measurement
    filters:
      - multiply: 10

#
# Charging Parameters
#

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: constant_voltage
    name: "Constant Voltage Charging"
    address: 0x0177
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: float_voltage
    name: "Float Charging Voltage"
    address: 0x0178
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: constant_current
    name: "Constant Voltage Charging Current"
    address: 0x0179
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: A
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: float_current
    name: "Float Charging Current"
    address: 0x017A
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: A
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: max_constant_current_time
    name: "Maximum Constant Current Time"
    address: 0x017B
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: h

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: max_constant_voltage_time
    name: "Maximum Constant Voltage Time"
    address: 0x017C
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: h

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: equalization_voltage
    name: "Equalization Voltage"
    address: 0x017E
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: equalization_time
    name: "Equalization Time"
    address: 0x017F
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: h

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: equalization_delay
    name: "Equalization Delay"
    address: 0x0180
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: h

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: equalization_interval
    name: "Equalization Interval"
    address: 0x0181
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: d

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: equalization_interval_counter
    name: "Equalization Interval Counter"
    address: 0x0183
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: h