###############################################################################
# WF_BAT
###############################################################################

text_sensor:

  - platform: template
    id: ${name}_battery_type
    name: "${name} Battery Type"
    lambda: |-
      switch ((uint16_t)id(${name}_battery_type_raw).state) {
        case 0: return {"Lead Acid"};
        case 1: return {"Flooded"};
        case 2: return {"Ternary Lithium"};
        case 3: return {"LiFePO4"};
        case 4: return {"Custom"};
        default: return {"Unknown"};
      }

  - platform: template
    id: ${name}_charging_status
    name: "${name} Charging Status"
    lambda: |-
      switch ((uint16_t)id(${name}_charging_status_raw).state) {
        case 0: return {"Not Charging"};
        case 1: return {"CC/CV"};
        case 2: return {"Float"};
        case 3: return {"Equalization"};
        default: return {"Unknown"};
      }

sensor:

#
# RAW
#

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_battery_type_raw
    internal: true
    address: 0x0150
    register_type: holding
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_charging_status_raw
    internal: true
    address: 0x0176
    register_type: holding
    value_type: U_WORD

#
# Battery
#

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_battery_percentage
    name: "${name} Battery Percentage"
    address: 0x0152
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "%"
    device_class: battery
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_positive_bus_voltage
    name: "${name} Positive Bus Voltage"
    address: 0x0154
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_positive_battery_voltage
    name: "${name} Positive Battery Voltage"
    address: 0x0155
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_positive_battery_discharge_current
    name: "${name} Positive Battery Discharge Current"
    address: 0x0156
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - lambda: |-
          return x < 0.0f ? -x : 0.0f;
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_positive_battery_charge_current
    name: "${name} Positive Battery Charge Current"
    address: 0x0157
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - lambda: |-
          return x > 0.0f ? x : 0.0f;
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_positive_overvoltage_alarm
    name: "${name} Positive Overvoltage Alarm Voltage"
    address: 0x0158
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_positive_low_voltage_alarm
    name: "${name} Positive Low Voltage Alarm Voltage"
    address: 0x0159
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_positive_output_cutoff_voltage
    name: "${name} Positive Output Cutoff Voltage"
    address: 0x015C
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_positive_output_cutoff_time
    name: "${name} Positive Output Cutoff Time"
    address: 0x015D
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: h

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_positive_battery_power
    name: "${name} Positive Battery Power"
    address: 0x015E
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: W
    device_class: power
    state_class: measurement
    filters:
      - multiply: 10

#
# Negative Battery
#

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_negative_bus_voltage
    name: "${name} Negative Bus Voltage"
    address: 0x0164
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_negative_battery_voltage
    name: "${name} Negative Battery Voltage"
    address: 0x0165
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_negative_battery_discharge_current
    name: "${name} Negative Battery Discharge Current"
    address: 0x0166
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_negative_battery_charge_current
    name: "${name} Negative Battery Charge Current"
    address: 0x0167
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_negative_overvoltage_alarm
    name: "${name} Negative Overvoltage Alarm Voltage"
    address: 0x0168
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_negative_low_voltage_alarm
    name: "${name} Negative Low Voltage Alarm Voltage"
    address: 0x0169
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_negative_output_cutoff_voltage
    name: "${name} Negative Output Cutoff Voltage"
    address: 0x016C
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_negative_output_cutoff_time
    name: "${name} Negative Output Cutoff Time"
    address: 0x016D
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: h

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_negative_battery_power
    name: "${name} Negative Battery Power"
    address: 0x016E
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: W
    device_class: power
    state_class: measurement
    filters:
      - multiply: 10

#
# Charging Parameters
#

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_constant_voltage
    name: "${name} Constant Voltage Charging"
    address: 0x0177
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_float_voltage
    name: "${name} Float Charging Voltage"
    address: 0x0178
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_constant_current
    name: "${name} Constant Voltage Charging Current"
    address: 0x0179
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: A
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_float_current
    name: "${name} Float Charging Current"
    address: 0x017A
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: A
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_max_constant_current_time
    name: "${name} Maximum Constant Current Time"
    address: 0x017B
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: h

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_max_constant_voltage_time
    name: "${name} Maximum Constant Voltage Time"
    address: 0x017C
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: h

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_equalization_voltage
    name: "${name} Equalization Voltage"
    address: 0x017E
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_equalization_time
    name: "${name} Equalization Time"
    address: 0x017F
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: h

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_equalization_delay
    name: "${name} Equalization Delay"
    address: 0x0180
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: h

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_equalization_interval
    name: "${name} Equalization Interval"
    address: 0x0181
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: d

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_equalization_interval_counter
    name: "${name} Equalization Interval Counter"
    address: 0x0183
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: h
