###############################################################################
# WF_INV
###############################################################################

sensor:

#
# Inverter Settings
#

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_inverter_voltage_setpoint
    name: "${name} Inverter Voltage Setpoint"
    address: 0x02A0
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_inverter_frequency_setpoint
    name: "${name} Inverter Frequency Setpoint"
    address: 0x02A1
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: Hz
    device_class: frequency
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

###############################################################################
# Phase A
###############################################################################

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_a_inverter_voltage
    name: "${name} Phase A Inverter Voltage"
    address: 0x02AA
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    filters: [{multiply: 0.1}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_a_inverter_frequency
    name: "${name} Phase A Inverter Frequency"
    address: 0x02AB
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: Hz
    device_class: frequency
    state_class: measurement
    accuracy_decimals: 2
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_a_inverter_current
    name: "${name} Phase A Inverter Current"
    address: 0x02AC
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    accuracy_decimals: 2
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_a_dc_component
    name: "${name} Phase A DC Component"
    address: 0x02AD
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: mV
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_a_daily_input_energy
    name: "${name} Phase A Daily Input Energy"
    address: 0x02AE
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_a_monthly_input_energy
    name: "${name} Phase A Monthly Input Energy"
    address: 0x02B0
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_a_total_input_energy
    name: "${name} Phase A Total Input Energy"
    address: 0x02B2
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_a_daily_output_energy
    name: "${name} Phase A Daily Output Energy"
    address: 0x02B4
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_a_monthly_output_energy
    name: "${name} Phase A Monthly Output Energy"
    address: 0x02B6
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_a_total_output_energy
    name: "${name} Phase A Total Output Energy"
    address: 0x02B8
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]

###############################################################################
# Phase B
###############################################################################

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_b_inverter_voltage
    name: "${name} Phase B Inverter Voltage"
    address: 0x02BA
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    filters: [{multiply: 0.1}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_b_inverter_frequency
    name: "${name} Phase B Inverter Frequency"
    address: 0x02BB
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: Hz
    device_class: frequency
    state_class: measurement
    accuracy_decimals: 2
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_b_inverter_current
    name: "${name} Phase B Inverter Current"
    address: 0x02BC
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    accuracy_decimals: 2
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_b_dc_component
    name: "${name} Phase B DC Component"
    address: 0x02BD
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: mV

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_b_inverter_daily_energy
    name: "${name} Phase B Inverter Daily Energy"
    address: 0x02C0
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_b_inverter_monthly_energy
    name: "${name} Phase B Inverter Monthly Energy"
    address: 0x02C2
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_b_inverter_total_energy
    name: "${name} Phase B Inverter Total Energy"
    address: 0x02C4
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]

###############################################################################
# Phase C
###############################################################################

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_c_inverter_voltage
    name: "${name} Phase C Inverter Voltage"
    address: 0x02CA
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    filters: [{multiply: 0.1}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_c_inverter_frequency
    name: "${name} Phase C Inverter Frequency"
    address: 0x02CB
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: Hz
    device_class: frequency
    state_class: measurement
    accuracy_decimals: 2
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_c_inverter_current
    name: "${name} Phase C Inverter Current"
    address: 0x02CC
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    accuracy_decimals: 2
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_c_dc_component
    name: "${name} Phase C DC Component"
    address: 0x02CD
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: mV

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_c_inverter_daily_energy
    name: "${name} Phase C Inverter Daily Energy"
    address: 0x02D0
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_c_inverter_monthly_energy
    name: "${name} Phase C Inverter Monthly Energy"
    address: 0x02D2
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_phase_c_inverter_total_energy
    name: "${name} Phase C Inverter Total Energy"
    address: 0x02D4
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]
