# Complete safe read-only register map.
packages:
  simplify: !include telemetry/simplify.yaml
  workmode: !include telemetry/workmode.yaml
  bat: !include telemetry/bat.yaml
  bms: !include telemetry/bms.yaml
  op: !include telemetry/op.yaml
  pv: !include telemetry/pv.yaml
  inv: !include telemetry/inv.yaml
  fan: !include telemetry/fan.yaml
  ntc: !include telemetry/ntc.yaml
