###############################################################################
# WF_INV
###############################################################################

sensor:


###############################################################################
# Phase A
###############################################################################

 

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_daily_input_energy
    name: "Phase A Daily Input Energy"
    address: 0x02AE
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_monthly_input_energy
    name: "Phase A Monthly Input Energy"
    address: 0x02B0
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_total_input_energy
    name: "Phase A Total Input Energy"
    address: 0x02B2
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_daily_output_energy
    name: "Phase A Daily Output Energy"
    address: 0x02B4
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_monthly_output_energy
    name: "Phase A Monthly Output Energy"
    address: 0x02B6
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_total_output_energy
    name: "Phase A Total Output Energy"
    address: 0x02B8
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]

