text_sensor:

  - platform: template
    name: "Fault Code 1 Status"
    update_interval: 2s
    lambda: |-
      const uint16_t code = (uint16_t) id(fault_code_1).state;
      if (code & (1 << 0)) return {"Mains soft start failure"};
      if (code & (1 << 1)) return {"Bus overvoltage"};
      if (code & (1 << 2)) return {"Bus undervoltage"};
      if (code & (1 << 3)) return {"Battery overcurrent"};
      if (code & (1 << 4)) return {"Overtemperature"};
      if (code & (1 << 5)) return {"Battery overvoltage"};
      if (code & (1 << 6)) return {"Battery soft start failure"};
      if (code & (1 << 7)) return {"Bus short circuit"};
      if (code & (1 << 8)) return {"Inverter soft start failure"};
      if (code & (1 << 9)) return {"Inverter overvoltage"};
      if (code & (1 << 10)) return {"Inverter undervoltage"};
      if (code & (1 << 11)) return {"Inverter short circuit"};
      if (code & (1 << 12)) return {"Negative power protection"};
      if (code & (1 << 13)) return {"Overload failure"};
      if (code & (1 << 14)) return {"Unit model and hardware incompatibility"};
      if (code & (1 << 15)) return {"No bootloader"};
      return {"OK"};

  - platform: template
    name: "Fault Code 2 Status"
    update_interval: 2s
    lambda: |-
      const uint16_t code = (uint16_t) id(fault_code_2).state;
      if (code & (1 << 0)) return {"Programming in progress"};
      if (code & (1 << 1)) return {"Photovoltaic reverse connection"};
      if (code & (1 << 2)) return {"Parallel serial number abnormal"};
      if (code & (1 << 3)) return {"Parallel communication abnormal"};
      if (code & (1 << 4)) return {"Excessive voltage difference between parallel batteries"};
      if (code & (1 << 5)) return {"Excessive voltage difference between parallel mains"};
      if (code & (1 << 6)) return {"Excessive frequency difference between parallel mains"};
      if (code & (1 << 7)) return {"Phase loss in parallel setting"};
      if (code & (1 << 8)) return {"Loss of parallel output synchronization"};
      if (code & (1 << 9)) return {"BMS fault"};
      if (code & (1 << 10)) return {"MCU fault"};
      if (code & (1 << 12)) return {"Inverter load abnormal"};
      return {"OK"};

  - platform: template
    name: "Alarm Code 1 Status"
    update_interval: 2s
    lambda: |-
      const uint16_t code = (uint16_t) id(alarm_code_1).state;
      if (code & (1 << 0)) return {"Battery not connected"};
      if (code & (1 << 1)) return {"Battery undervoltage"};
      if (code & (1 << 2)) return {"Battery low voltage"};
      if (code & (1 << 3)) return {"Charger short circuit"};
      if (code & (1 << 5)) return {"Battery overcharge"};
      if (code & (1 << 6)) return {"BMS lost"};
      if (code & (1 << 7)) return {"Overtemperature"};
      if (code & (1 << 8)) return {"Fan stalled"};
      if (code & (1 << 9)) return {"EEPROM fault"};
      if (code & (1 << 10)) return {"Overload"};
      if (code & (1 << 11)) return {"Generator waveform abnormal"};
      if (code & (1 << 12)) return {"Weak PV energy"};
      if (code & (1 << 13)) return {"Parallel synchronization signal lost"};
      if (code & (1 << 14)) return {"Parallel setting phase loss"};
      if (code & (1 << 15)) return {"Parallel version incompatible"};
      return {"OK"};

  - platform: template
    name: "Alarm Code 2 Status"
    update_interval: 2s
    lambda: |-
      const uint16_t code = (uint16_t) id(alarm_code_2).state;
      if (code & (1 << 0)) return {"Parallel communication error"};
      if (code & (1 << 1)) return {"Excessive voltage difference or frequency in parallel operation"};
      if (code & (1 << 2)) return {"Low SOC shutdown"};
      if (code & (1 << 3)) return {"Low SOC alarm"};
      if (code & (1 << 4)) return {"Excessive battery voltage difference or not connected in parallel operation"};
      if (code & (1 << 5)) return {"Battery short circuit"};
      if (code & (1 << 6)) return {"Battery voltage below starting voltage"};
      if (code & (1 << 7)) return {"Generator overload"};
      if (code & (1 << 8)) return {"Generator undervoltage"};
      if (code & (1 << 9)) return {"Generator overvoltage"};
      if (code & (1 << 10)) return {"CT reverse connection"};
      if (code & (1 << 11)) return {"Unstable mains power"};
      return {"OK"};


sensor:

###############################################################################
# Status / Faults / Alarms
###############################################################################

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: software_version
    name: "Software Version"
    address: 0x0040
    register_type: holding
    value_type: U_WORD
    entity_category: diagnostic


  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: fault_code_1
    name: "Fault Code 1"
    address: 0x0046
    register_type: holding
    value_type: U_WORD
    entity_category: diagnostic

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: fault_code_2
    name: "Fault Code 2"
    address: 0x0047
    register_type: holding
    value_type: U_WORD
    entity_category: diagnostic

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: alarm_code_1
    name: "Alarm Code 1"
    address: 0x0048
    register_type: holding
    value_type: U_WORD
    entity_category: diagnostic

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: alarm_code_2
    name: "Alarm Code 2"
    address: 0x0049
    register_type: holding
    value_type: U_WORD
    entity_category: diagnostic

###############################################################################
# Phase A
###############################################################################

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_grid_voltage
    name: "Phase A Grid Voltage"
    address: 0x0050
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_grid_current
    name: "Phase A Grid Current"
    address: 0x0051
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "A"
    device_class: current
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_grid_frequency
    name: "Phase A Grid Frequency"
    address: 0x0052
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "Hz"
    device_class: frequency
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_grid_power
    name: "Phase A Grid Power"
    address: 0x0053
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_load_voltage
    name: "Phase A Load Voltage"
    address: 0x0058
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_load_current
    name: "Phase A Load Current"
    address: 0x0059
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "A"
    device_class: current
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_load_frequency
    name: "Phase A Load Frequency"
    address: 0x005A
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "Hz"
    device_class: frequency
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_load_active_power
    name: "Phase A Load Active Power"
    address: 0x005B
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_load_apparent_power
    name: "Phase A Load Apparent Power"
    address: 0x005C
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "VA"
    device_class: apparent_power
    state_class: measurement

