###############################################################################
# WF_THERMAL
###############################################################################

binary_sensor:

  - platform: template
    id: fan_fault
    name: "Fan Fault"
    entity_category: diagnostic
    device_class: problem
    lambda: |-
      return id(fan_status_raw).state != 0;

sensor:

###############################################################################
# Fan
###############################################################################

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: fan_speed
    name: "Fan Speed"
    address: 0x0320
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "%"
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: fan_status_raw
    internal: true
    address: 0x0321
    register_type: holding
    value_type: U_WORD
    entity_category: diagnostic

###############################################################################
# Temperatures
###############################################################################

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: temperature_pv
    name: "Temperature PV"
    address: 0x0330
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1


  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: temperature_inverter
    name: "Temperature Inverter"
    address: 0x0331
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1


  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: temperature_charger
    name: "Temperature Charger"
    address: 0x0332
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1


  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: temperature_charger2
    name: "Temperature Charger 2"
    address: 0x0333
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: temperature_ambient
    name: "Temperature Ambient"
    address: 0x0334
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

