###############################################################################
# WF_INV
###############################################################################

sensor:

###############################################################################
# Phase A
###############################################################################

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_input_energy_daily
    name: "Phase A Input Energy Daily"
    address: 0x02AE
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_input_energy_monthly
    name: "Phase A Input Energy Monthly"
    address: 0x02B0
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_input_energy_total
    name: "Phase A Input Energy Total"
    address: 0x02B2
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_output_energy_daily
    name: "Phase A Output Energy Daily"
    address: 0x02B4
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_output_energy_monthly
    name: "Phase A Output Energy Monthly"
    address: 0x02B6
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: phase_a_output_energy_total
    name: "Phase A Output Energy Total"
    address: 0x02B8
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters: [{multiply: 0.01}]

