###########
# Battery #
###########

sensor:

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_battery_percentage
    name: "${name} Battery Percentage"
    skip_updates: 5
    address: 0x0152
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "%"
    device_class: battery
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_bus_voltage
    name: "${name} Bus Voltage"
    skip_updates: 5
    address: 0x0154
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_battery_voltage
    name: "${name} Battery Voltage"
    skip_updates: 5
    address: 0x0155
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_battery_discharge_current
    name: "${name} Battery Discharge Current"
    address: 0x0156
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - lambda: |-
          return x < 0.0f ? -x : 0.0f;
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_battery_charge_current
    name: "${name} Battery Charge Current"
    address: 0x0157
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - lambda: |-
          return x > 0.0f ? x : 0.0f;
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_battery_current
    name: "${name} Battery Current"
    address: 0x0194
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "A"
    device_class: current
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_bms_temperature
    name: "${name} BMS Temperature"
    skip_updates: 5
    address: 0x0195
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_battery_soh
    name: "${name} Battery SOH"
    skip_updates: 5
    address: 0x0197
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "%"
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_battery_capacity
    name: "${name} Battery Capacity"
    skip_updates: 5
    address: 0x0198
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "Ah"

  - platform: template
    id: ${name}_battery_power
    name: "${name} Battery Power"
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    icon: mdi:battery
    accuracy_decimals: 0
    update_interval: 15s
    lambda: |-
      if (isnan(id(${name}_battery_voltage).state) || isnan(id(${name}_battery_current).state)) {
        return {};
      }
      return id(${name}_battery_voltage).state * id(${name}_battery_current).state;
