sensor:

###############################################################################
# Inverter Mains and Load Measurements
###############################################################################

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_mains_energy_daily
    skip_updates: 10
    name: "${name} Mains Energy Daily"
    address: 0x02AE
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_mains_energy_monthly
    skip_updates: 10
    name: "${name} Mains Energy Monthly"
    address: 0x02B0
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_mains_energy_total
    skip_updates: 10
    name: "${name} Mains Energy Total"
    address: 0x02B2
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_load_energy_daily
    skip_updates: 10
    name: "${name} Load Energy Daily"
    address: 0x02B4
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_load_energy_monthly
    skip_updates: 10
    name: "${name} Load Energy Monthly"
    address: 0x02B6
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_load_energy_total
    skip_updates: 10
    name: "${name} Load Energy Total"
    address: 0x02B8
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.01

###############################################################################
# Inverter PV Measurements
###############################################################################

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_pv_energy_today
    skip_updates: 10
    name: "${name} PV Energy Today"
    address: 0x009C
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "KWh"
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_pv_daily_energy
    skip_updates: 10
    name: "${name} PV Daily Energy"
    address: 0x0267
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_pv_monthly_energy
    skip_updates: 10
    name: "${name} PV Monthly Energy"
    address: 0x0269
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_pv_yearly_energy
    skip_updates: 10
    name: "${name} PV Yearly Energy"
    address: 0x026B
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: sms_0
    id: ${name}_pv_total_energy
    skip_updates: 10
    name: "${name} PV Total Energy"
    address: 0x026D
    register_count: 2
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

